ToDoList_App/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Todo.urls')),
    path('accounts/', include('accounts.urls'))
]

Todo/urls.py
from django.urls import path
from . import views

app_name='todo'
urlpatterns = [
    path('', views.homepage, name='index'),
    path('list/', views.list.as_view(), name='list'),
    path('add_item/', views.add_item, name='add'),
    path('delete/<int:item_id>',views.delete_item, name='del')
]

accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

Todo/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class TodoDB(models.Model):
    item_text = models.CharField(max_length=100)
    date_added = models.DateTimeField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return(self.item_text)

accounts/models.py
from django.db import models

# Create your models here.

Todo/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
# Create your views here.
from django.http import HttpResponseRedirect
from .models import TodoDB
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.http import Http404

from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin

def homepage(request):
    return render(request, 'todo/homepage.html')



# @login_required ---We can't use the login_required decorator on a class like that. We need to use method_decorator or pass LoginRequiredMixin
# When using class-based views, you can achieve the same behavior as with login_required by using the LoginRequiredMixin. This mixin should be at the leftmost position in the inheritance list.

# @method_decorator(login_required, name='dispatch')
class list(LoginRequiredMixin, generic.ListView):

    template_name = 'todo/index.html'
    context_object_name ='context'

    def get_queryset(self):
        all_item = TodoDB.objects.filter(owner=self.request.user).order_by('-date_added')
        return all_item


@login_required
# //login_required(redirect_field_name='next', login_url=None)
#login_required redirects the non-logged in user to the page passed in its login_url argument or whatever we have defined in settings.py >>LOGIN_URL
def add_item(request):
    item_name=TodoDB.objects.create(item_text=request.POST['item'], date_added=timezone.now(), owner=request.user)
    item_name.save()
    print("Message from the view function- created item with item id: "+ str(item_name.id))
    return redirect('todo:list')

@login_required
def delete_item(request, item_id):
    if TodoDB.objects.get(id=item_id).owner==request.user:
        TodoDB.objects.get(id=item_id).delete()
    else:
        raise Http404
    return redirect('todo:list')
#if redirect to a view needed some arguments, they could be passed like this
# return redirect(viewArticles, year = "2045", month = "02")

accounts/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.contrib.auth.models import User, auth
from django.contrib import messages

def register(request):
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password1 = request.POST['password1']
            password2 = request.POST['password2']
            email = request.POST['email']
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']

            if password1!=password2:
                messages.error(request, "Passwords do not match!")
                return redirect('accounts:register')
            elif User.objects.filter(username=username).exists():
                messages.error(request, "Username already taken!")
                return redirect('accounts:register')
            elif User.objects.filter(email=email).exists():
                messages.error(request, "Email already registered!")
                return redirect('accounts:register')
            else:
                user_created = User.objects.create_user(username=username, password=password1, email=email, first_name=first_name, last_name=last_name)
                user_created.save();
                messages.info(request, "Thanks, user created")
                return redirect('accounts:login')
        except(ValueError):
            messages.error(request,"All fields need to be filled!")
            return redirect('accounts:register')


    else:
        return render(request, 'accounts/register.html')


def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']

        user_authentication = auth.authenticate(username=username, password=password)
        if user_authentication:
            auth.login(request, user_authentication)
            return redirect('todo:list')

        else:
            messages.error(request, "Username or Password do not match, try again!")
            return redirect('accounts:login')

    else:
        return render(request, 'accounts/login.html')

def logout(request):
    auth.logout(request)
    return redirect('todo:index')

Todo/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <div class="container">
        <h3> User Login:</h3></br>
        <div class="foat-start">
            <div class= "form-text">Username :</div>
            <div class="form-text"><input type="text" name="username" class="form-control"></div>

            <div class="form-text">Password :</div>
            <div class="form-text"><input type="password" name="password" class="form-control"></div>
        </div>

        <div class="float-end">
            <button type="submit" class="btn btn-primary">Log In</button>
        </div>

        <div class="text-danger">
           {% for message in messages %}
                {{message}}
          {% endfor %}
      </div>

    </div>

</form>


{% endblock %}

Todo/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<form class="form-inline" action="{% url 'accounts:register' %}" method="POST">
{% csrf_token %}

<div class="container">
    <h3> User Registeration:</h3></br>


        <div class=" form-text ">Enter Your First Name:<input type="text" name="first_name" class="form-control"> </div>

        <div class="form-text">Enter Your Last Name:<input type="text" name="last_name" class="form-control"> </div>

        <div class="form-text">Enter desired Username:<input type="text" name="username" class="form-control"> </div>

        <div class="form-text">Enter desired password:<input type="password" name="password1" class="form-control"> </div>

        <div class="form-text">ReEnter the password:<input type="password" name="password2" class="form-control"> </div>

        <div class="form-text">Enter email:<input type="email" name="email" class="form-control"> </div>


     <div class="float-end">
            <button type="submit" class="btn btn-primary">Register</button>

        </div>

      <div class="text-danger">
           {% for message in messages %}
                {{message}}
          {% endfor %}
      </div>
</div>

</form>
{% endblock %}

Todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to Gary's To do App</title>
<!--    Adding Boot strap config-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</head>
<body>


<nav class="navbar navbar-dark bg-primary"  >
    <div class="container-fluid">
        {% if user.is_authenticated %}

                    <h1 class="navbar-brand float-start"><b>{{user.first_name}}'s Todo List</b></h1>
                <h5 class="navbar-brand float-end"><b>Welcome, {{user.first_name}}!</b></h5>
        <span class="form-text">Last login @:{{ user.last_login }}</span>
                    <form action="{% url 'accounts:logout' %}">
                        <button class='btn btn-danger btn-sm' type="submit">Logout</button>
                    </form>


        {% else %}
                <h1 class="navbar-brand"  ><b>My Todo List</b></h1>
               <form action="{% url 'accounts:login' %}">
                    <button class='btn btn-info btn-sm ' type="submit"><b>Login</b></button>
               </form>
               <form action="{% url 'accounts:register' %}">
                    <button class='btn btn-warning btn-sm' type="submit"><b>Register</b></button>
               </form>
            {% endif %}

    </div>
</nav>

<div class="container">
{% block content %}

{% endblock %}
</div>
</body>
</html>

Todo/templates/todo/homepage.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
<br><br>
<a href="{% url 'todo:list' %}"><b>View Your Todo list</b></a>
{% else %}
            <h5>Sorry! You must login to view your items.</h5>
            <span class="align-top">
                <a href="{% url 'accounts:login' %}">
                    <button class='btn btn-info btn-sm ' type="submit"><b>Login</b></button>
               </a>
                </span>
                <span class="align-top">
                <a href="{% url 'accounts:register' %}">
                    <button class='btn btn-warning btn-sm' type="submit"><b>Register</b></button>
               </a>
                </span>

{% endif %}
{% endblock %}

Todo/templates/todo/index.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}

            <form class='form-inline' method="post" action= "{% url 'todo:add' %}">
                {% csrf_token %}

                <div class="mt-4">
                    <label for="a" class="navbar-brand" ><b>Add To do Items:</b></label>
                    <input type="search" name="item" id="a" placeholder="Type your to do items" class="form-control"></br>
                        <div class="form-text">Add your to do items here with in 100 characters.</div>
              </div>
              <button type="submit" class="btn btn-primary">Add Entry</button>

            </form>

            <div class="row mt-5">
                <div class="col">
                <h5>Here is the list of items you have already added:</h5>
                     <ul class="list-group">
                            {% for context_element in context %}
                         <li class="list-group-item list-group-item-info">
                             <div class="fs-5 float-start" >
                            <!--Inserting icon-->
                                     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard-check" viewBox="0 0 16 16">
                                      <path fill-rule="evenodd" d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                                      <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                                      <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                                    </svg>
                            <!-- end-->

                             &nbsp;&nbsp;{{context_element}}</div>
                                    <div class="float-end fw-lighter  ">
                                        <form method="POST" action="{% url 'todo:del' context_element.id %}">
                                        {% csrf_token %}
                                            -Posted: {{context_element.date_added}}&nbsp;&nbsp;
                                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                        </form>
                                    </div>
                                </li>
                             {% endfor %}
                     </ul>
                </div>
            </div>
{% else %}
            <h5>Sorry! You must login to view your items.</h5>
            <span class="align-top">
                <a href="{% url 'accounts:login' %}">
                    <button class='btn btn-info btn-sm ' type="submit"><b>Login</b></button>
               </a>
                </span>
                <span class="align-top">
                <a href="{% url 'accounts:register' %}">
                    <button class='btn btn-warning btn-sm' type="submit"><b>Register</b></button>
               </a>
                </span>

{% endif %}
{% endblock %}